"""The Free2Genius HTTP service.

Run: `uvicorn f2g.api.main:app --reload`

One process serves scoring, agent generation, experiment assignment, event
capture, analysis and the audit trail. At this scale a single process is the
right answer; the seams that would need splitting later (the store, the
provider, the scoring service) are already behind interfaces.
"""
from __future__ import annotations

import logging
import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from f2g import config
from f2g.api import service
from f2g.api.schemas import (
    BatchScoreRequest,
    ChatRequest,
    CohortResponse,
    EventRequest,
    NudgeRequest,
    PowerRequest,
    ScoreResponse,
)
from f2g.api.store import EventStore
from f2g.experiment import analysis
from f2g.experiment.assign import DEFAULT_EXPERIMENT, assign

log = logging.getLogger(__name__)

SYNTHETIC_NOTICE = (
    "All data served by this API is synthetic, generated by f2g/data/generate.py. "
    "It is not Albert data and the pricing is illustrative."
)

@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    """Fail at startup rather than on the first request.

    A service that starts happily and then serves wrong numbers is worse than
    one that refuses to start and names the command to run.
    """
    state = service.health()
    if not state["models"]["available"]:
        raise RuntimeError(
            f"model artifacts unavailable: {state['models']['detail']}. "
            "Run `python -m f2g.data.generate && python -m f2g.ml.train` first."
        )
    log.info("models %s | llm %s", state["models"]["detail"], state["llm"].get("provider"))
    yield


app = FastAPI(
    lifespan=lifespan,
    title="Free2Genius",
    version="1.0.0",
    description=(
        "Propensity-plus-agent growth system. An uplift model decides who to nudge; "
        "a locally-hosted, evidence-grounded agent decides what to say.\n\n"
        f"**{SYNTHETIC_NOTICE}**\n\n"
        "No authentication is configured. This is a demonstration service and must "
        "not be exposed publicly."
    ),
)

# The console is served separately in development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

store = EventStore()


# --- health ---------------------------------------------------------------

@app.get("/health", tags=["ops"])
def health() -> dict[str, Any]:
    return {**service.health(), "notice": SYNTHETIC_NOTICE}


# --- scoring --------------------------------------------------------------

@app.get("/score/{user_id}", response_model=ScoreResponse, tags=["scoring"])
def score(user_id: str) -> Any:
    try:
        return service.score_user(user_id)
    except KeyError:
        raise HTTPException(404, f"unknown user_id: {user_id}")


@app.post("/score/batch", tags=["scoring"])
def score_batch(req: BatchScoreRequest) -> dict[str, Any]:
    scored, missing = [], []
    for uid in req.user_ids:
        try:
            scored.append(service.score_user(uid))
        except KeyError:
            missing.append(uid)
    return {"scored": scored, "unknown_user_ids": missing}


@app.get("/cohort", response_model=CohortResponse, tags=["scoring"])
def cohort(
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
    decision: str | None = None,
    segment: str | None = None,
    sort_by: str = Query("uplift", pattern="^(uplift|propensity|estimated_saving_90d)$"),
) -> Any:
    frame = service.scored_live()
    if decision:
        frame = frame[frame.decision == decision]
    if segment:
        frame = frame[frame.segment == segment]
    frame = frame.sort_values(sort_by, ascending=False, kind="stable")

    page = frame.iloc[offset : offset + limit]
    rows = [
        {
            "user_id": r.user_id, "segment": r.segment, "income_band": r.income_band,
            "uplift": float(r.uplift),
            "propensity": float(r.propensity) if r.propensity == r.propensity else None,
            "estimated_saving_90d": float(r.estimated_saving_90d),
            "net_position_90d": float(r.net_position_90d),
            "decision": r.decision, "reason_detail": r.reason_detail or "",
        }
        for r in page.itertuples()
    ]
    return {
        "total": int(len(frame)), "offset": offset, "limit": limit, "rows": rows,
        "summary": service.live_policy_summary()["summary"],
    }


@app.get("/policy/summary", tags=["policy"])
def policy_summary() -> dict[str, Any]:
    return service.live_policy_summary()


# --- agent ----------------------------------------------------------------

@app.post("/agent/nudge/{user_id}", tags=["agent"])
def nudge(user_id: str, req: NudgeRequest | None = None) -> dict[str, Any]:
    req = req or NudgeRequest()
    try:
        result = service.nudge(user_id, req.provider, refresh=req.refresh)
    except KeyError:
        raise HTTPException(404, f"unknown user_id: {user_id}")
    if not result.get("cached"):
        store.record_generation(str(uuid.uuid4()), result)
    return result


@app.post("/agent/chat", tags=["agent"])
def chat(req: ChatRequest) -> dict[str, Any]:
    try:
        result = service.chat(req.user_id, req.message, req.history, req.provider)
    except KeyError:
        raise HTTPException(404, f"unknown user_id: {req.user_id}")
    store.record_generation(str(uuid.uuid4()), result)
    return result


# --- experiment -----------------------------------------------------------

@app.get("/experiment", tags=["experiment"])
def experiment_config() -> dict[str, Any]:
    e = DEFAULT_EXPERIMENT
    return {
        "id": e.id,
        "arms": [{"name": a.name, "share": a.share, "description": a.description} for a in e.arms],
        "primary_metric": e.primary_metric,
        "guardrail_metric": e.guardrail_metric,
        "guardrail_margin": e.guardrail_margin,
        "planned_horizon_days": e.planned_horizon_days,
    }


@app.post("/experiment/assign/{user_id}", tags=["experiment"])
def assign_user(user_id: str) -> dict[str, Any]:
    variant = assign(user_id, DEFAULT_EXPERIMENT)
    stored = store.record_assignment(user_id, DEFAULT_EXPERIMENT.id, variant)
    return {"user_id": user_id, "experiment_id": DEFAULT_EXPERIMENT.id, "variant": stored}


@app.post("/experiment/events", tags=["experiment"])
def record_event(req: EventRequest) -> dict[str, Any]:
    exp_id = req.experiment_id or DEFAULT_EXPERIMENT.id
    try:
        return store.record_event(
            idempotency_key=req.idempotency_key, user_id=req.user_id,
            experiment_id=exp_id, event_type=req.event_type, value=req.value,
            out_of_window=req.out_of_window,
        )
    except KeyError as exc:
        raise HTTPException(409, str(exc))


@app.get("/experiment/summary", tags=["experiment"])
def experiment_summary(experiment_id: str | None = None, horizon_reached: bool = False) -> dict[str, Any]:
    exp = DEFAULT_EXPERIMENT
    rows = store.counts(experiment_id or exp.id)
    by_arm = {r["variant"]: r for r in rows}

    def stats_for(arm: str) -> analysis.ArmStats:
        r = by_arm.get(arm, {})
        return analysis.arm_stats(
            arm, int(r.get("n", 0)), int(r.get("conversions", 0)),
            int(r.get("retained", 0)), int(r.get("retention_observed", 0)),
        )

    treatment = stats_for("agent_concierge")
    control = stats_for("generic_upsell")
    holdout = stats_for("holdout")

    conversion = analysis.compare(treatment, control)
    retention = analysis.compare(
        analysis.arm_stats(treatment.arm, max(treatment.converted_with_retention_data, 1),
                           treatment.retained),
        analysis.arm_stats(control.arm, max(control.converted_with_retention_data, 1),
                           control.retained),
    )
    verdict = analysis.stopping_verdict(
        conversion, retention,
        guardrail_margin=exp.guardrail_margin, horizon_reached=horizon_reached,
    )

    return {
        "experiment_id": experiment_id or exp.id,
        "arms": [s.to_dict() for s in (treatment, control, holdout)],
        "conversion": conversion.to_dict(),
        "retention_guardrail": {**retention.to_dict(), "margin": exp.guardrail_margin},
        "verdict": verdict,
        "timeseries": store.timeseries(experiment_id or exp.id),
        "notice": SYNTHETIC_NOTICE,
    }


@app.post("/experiment/power", tags=["experiment"])
def power(req: PowerRequest) -> dict[str, Any]:
    return analysis.sample_size(
        req.baseline_rate, req.mde_relative, alpha=req.alpha, power=req.power
    )


# --- audit and telemetry --------------------------------------------------

@app.get("/audit/{user_id}", tags=["ops"])
def audit(user_id: str) -> dict[str, Any]:
    """Everything recorded about one user — the answer to a complaint."""
    return store.explain(user_id)


@app.get("/telemetry", tags=["ops"])
def telemetry(limit: int = Query(500, ge=1, le=5000)) -> dict[str, Any]:
    from f2g.api.telemetry import summarise

    return summarise(store.generation_telemetry(limit))
