"""Generate the model card from current evaluation output.

A hand-maintained model card is a document that was true once. It drifts the
moment someone retrains, and nobody notices because nothing checks it. So this
renders the card from the artifacts the pipeline actually produced, and
`tests/test_governance.py` asserts that the committed card matches what the
current metrics would generate.

That makes a stale card a failing test rather than a discovery during a review.

Run: `python -m f2g.governance.model_card`
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

from f2g import config

REPORT_DIR = config.ARTIFACT_DIR / "reports"
EVAL_DIR = config.ARTIFACT_DIR / "evals"
CARD_PATH = Path(__file__).resolve().parent.parent.parent / "docs" / "governance" / "MODEL_CARD.md"


class ArtifactsMissing(RuntimeError):
    pass


def _load(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise ArtifactsMissing(
            f"{path} not found. Regenerate with:\n"
            "  python -m f2g.data.generate && python -m f2g.ml.train "
            "&& python -m f2g.ml.run_policy && python -m f2g.evals.run"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def render(
    model_report: dict[str, Any],
    policy_report: dict[str, Any],
    eval_report: dict[str, Any] | None,
) -> str:
    m = model_report
    prod = m["production_estimator"]
    qini_key = {"uplift_x": "uplift (X-learner)", "uplift_t": "uplift (T-learner)",
                "uplift_s": "uplift (S-learner)"}[prod]
    rec_key = {"uplift_x": "x_learner", "uplift_t": "t_learner", "uplift_s": "s_learner"}[prod]
    rec = m["tau_recovery"][rec_key]
    ceiling = m["qini"]["oracle (true tau)"]["coefficient"]
    policy = policy_report["decide"]["summary"]
    gate = policy_report["decide"]["gate_cost"]
    ev = eval_report["metrics"] if eval_report else None

    lines = [
        "# Model Card — Free2Genius",
        "",
        "<!-- GENERATED FILE. Do not edit by hand.",
        "     Regenerate: python -m f2g.governance.model_card",
        "     A test asserts this file matches current evaluation output. -->",
        "",
        f"**Generated**: {date.today().isoformat()} · "
        f"**Data fingerprint**: `{m['data_fingerprint']}` · **Seed**: `{m['seed']}`",
        "",
        "> **All data is synthetic.** Generated by `f2g/data/generate.py`. No Albert data, "
        "customer data or production model was used. Pricing is an illustrative placeholder. "
        "Every number below is reproducible from a clean checkout.",
        "",
        "## What this system is",
        "",
        "Two models and one agent, used together to decide which free users to invite to a "
        "paid subscription and what to say to them.",
        "",
        "| Component | Role |",
        "|---|---|",
        "| Propensity model | `P(convert)`. A **diagnostic baseline and explanation feature only**. It never decides who is contacted. |",
        f"| Uplift model ({prod}) | Conditional average treatment effect. **This is the targeting signal.** |",
        "| Targeting policy | Turns the effect estimate into a decision under budget, do-no-harm, value-fit and fairness constraints. |",
        "| Concierge agent | Writes the per-user explanation, grounded in that user's own fee history. |",
        "",
        "## Intended use",
        "",
        "- Selecting which free-tier users to invite to the paid tier in a batch cycle.",
        "- Generating a per-user explanation of which features would save them money.",
        "- Deciding, explicitly, **not** to contact users the subscription would not benefit.",
        "",
        "## Out-of-scope use",
        "",
        "- Any credit, lending, underwriting or eligibility decision. This system must never "
        "influence access to money.",
        "- Pricing individual users differently.",
        "- Any decision with a legal or similarly significant effect on a person.",
        "- Financial, tax, investment or debt advice. The agent declines these before any "
        "model runs (`f2g/agent/scope.py`).",
        "- Operating without the value-fit gate. Disabling it changes what the system is.",
        "",
        "## Training data",
        "",
        f"- Synthetic pilot cohort, {m['split']['train'] + m['split']['valid'] + m['split']['test']:,} "
        f"labelled users, split {m['split']['train']:,} train / {m['split']['valid']:,} validation "
        f"/ {m['split']['test']:,} test.",
        "- Randomised 50/50 nudge assignment. **Randomisation is what identifies the treatment "
        "effect**; with observational data the uplift estimates would require an assumption "
        "this system does not make.",
        "- 26 behavioural and demographic features over a trailing 90-day window.",
        "- Identifiers, outcomes and the simulation's ground-truth variables are excluded from "
        "features, asserted by `tests/test_no_leakage.py`.",
        "",
        "## Performance",
        "",
        "### Propensity model (held-out, control arm)",
        "",
        "| metric | value |",
        "|---|---|",
        f"| ROC AUC | {m['propensity']['roc_auc']:.4f} |",
        f"| PR AUC | {m['propensity']['pr_auc']:.4f} |",
        f"| Log loss | {m['propensity']['log_loss']:.4f} |",
        f"| Expected calibration error | {m['propensity']['calibration_error']:.4f} |",
        "",
        f"### Uplift model — {prod}",
        "",
        "AUC is deliberately **not** reported. The treatment effect is never observed for an "
        "individual, so a discrimination metric against a different label would be a "
        "reassuring number about the wrong quantity.",
        "",
        "| metric | value |",
        "|---|---|",
        f"| Qini coefficient | {m['qini'][qini_key]['coefficient']:.4f} |",
        f"| Qini as a share of the achievable ceiling | {m['qini'][qini_key]['coefficient'] / ceiling:.0%} |",
        f"| Spearman correlation with true effect | {rec['spearman']:.4f} |",
        f"| Sign agreement with true effect | {rec['sign_agreement']:.4f} |",
        f"| Propensity baseline Qini | {m['qini']['propensity']['coefficient']:.4f} |",
        f"| Bottom-decile realised uplift | "
        f"{m['uplift_deciles_x'][-1]['realised_uplift'] * 100:+.2f} pp |",
        "",
        "The bottom-decile figure is the do-no-harm check: a working estimator locates users "
        "whom contact makes *less* likely to convert, so the policy can withhold contact from "
        "them.",
        "",
        "## Targeting policy outcome",
        "",
        "| | |",
        "|---|---|",
        f"| Candidates | {policy['candidates']:,} |",
        f"| Selected for contact | {policy['selected']:,} |",
        f"| Binding constraint | **{policy['binding_constraint']}** |",
        f"| Suppressed by value fit | {policy['suppressed_by_reason'].get('value_fit', 0):,} |",
        f"| Suppressed for non-positive uplift | {policy['suppressed_by_reason'].get('negative_uplift', 0):,} |",
        f"| Mean estimated 90-day saving, contacted | ${policy['mean_saving_selected']:.2f} |",
        f"| Same, with the value-fit gate disabled | ${gate['mean_saving_selected_ungated']:.2f} |",
        f"| Expected conversions forgone to the gate | {gate['expected_conversions_forgone']:.1f} |",
        "",
        "The gate costs real conversions. That trade is the point and it is reported in both "
        "directions rather than only where it flatters the system.",
        "",
        "## Fairness",
        "",
        "Monitored across income bands. The report separates gaps already present in the "
        "population from gaps the policy introduces — conflating them is how fairness "
        "reporting becomes decorative.",
        "",
        "| | |",
        "|---|---|",
        f"| Contact-rate gap (max − min band) | {policy['contact_rate_gap']:.4f} |",
        f"| Eligible-rate gap (population property) | {policy['eligible_rate_gap']:.4f} |",
        f"| Tolerance | {policy_report['config']['parity_tolerance']:.3f} |",
        f"| Flagged | {'**YES**' if policy['fairness_flag'] else 'no'} |",
        "",
        "Per-band discrimination and calibration are reported in "
        "`artifacts/reports/model_evaluation.md`. A parity-constrained selection mode is "
        "available and its cost in expected conversions is reported when used.",
        "",
    ]

    if ev:
        lines += [
            "## Agent safety evaluation",
            "",
            f"Golden case set of {ev['cases']} cases across 8 categories, run on "
            f"`{ev['provider']}` ({ev['model']}).",
            "",
            "| metric | value | gate |",
            "|---|---|---|",
            f"| Grounding violations reaching output | {ev['grounding_violations']} | must be 0 |",
            f"| Injection resistance | {ev['injection_resistance_rate']:.2f} | must be 1.00 |",
            f"| Prohibited-advice refusal | {ev['refusal_rate']:.2f} | must be ≥ 0.98 |",
            f"| 'Not worth it' stated where applicable | {ev['not_worth_it_rate']:.2f} | tracked |",
            f"| Tool selection accuracy | {ev['tool_selection_accuracy']:.2f} | tracked |",
            f"| Guardrail block rate | {ev['guardrail_block_rate']:.2f} | > 0.15 investigated |",
            f"| Degradation rate | {ev['degradation_rate']:.2f} | tracked |",
            "",
            "A grounding violation fails the build. It is not a metric to improve over time; "
            "it is a release blocker.",
            "",
        ]

    lines += [
        "## Known limitations",
        "",
        "1. **Synthetic data.** Every figure here describes a simulated population. Real "
        "behaviour is messier, and the treatment effect would be smaller and noisier.",
        "2. **Randomisation is assumed.** The uplift estimates depend on the pilot being "
        "randomised. An observational cohort would need a propensity-of-treatment model whose "
        "error would propagate into the effect estimate.",
        "3. **The X-learner needs the treatment propensity.** Ours is a known constant. In "
        "production it would be estimated, adding a second source of error.",
        "4. **Savings are estimates.** The estimator is deliberately conservative (overdraft "
        "coverage below 1.0, a cancellation rate assumption), but it cannot know what a user "
        "will actually do.",
        "5. **A small local model under-investigates.** Measured on this repository, both the "
        "1.5B and 3B models sometimes answered without reading the fee ledger. The agent now "
        "gathers required evidence itself, which fixes the outcome but means the model's own "
        "tool selection is weaker than the metric implies on its own.",
        "6. **The judge may mark its own homework.** When the judge runs on the same local "
        "model as the agent, their errors correlate. Judge scores track relative change and "
        "never gate a release.",
        "7. **No human review loop is implemented.** A real deployment needs sampled human "
        "review of generated messages before and during rollout.",
        "8. **Fairness is monitored on one axis.** Income band is what this synthetic "
        "population offers. A real programme would decide with legal which attributes may be "
        "monitored and which may never be used.",
        "",
        "## Failure modes and what catches them",
        "",
        "| Failure | Control | Where |",
        "|---|---|---|",
        "| Invented fee or price in generated text | Numeric value ledger; unmatched figures block the message | `f2g/agent/guardrails.py` |",
        "| Model performs arithmetic on money | Savings come only from `estimate_savings` | `f2g/agent/tools.py` |",
        "| Invented product feature | Catalog enum in the decode grammar makes it unrepresentable | `f2g/llm/grammar.py` |",
        "| Prompt injection redirecting the agent | User identity bound at construction, absent from every tool schema | `f2g/agent/tools.py` |",
        "| Out-of-scope financial advice | Declined before any model runs | `f2g/agent/scope.py` |",
        "| Model answers without evidence | Required evidence gathered by the agent if the model skips it | `f2g/agent/concierge.py` |",
        "| Degenerate repetition | Coherence check blocks and degrades | `f2g/agent/guardrails.py` |",
        "| Targeting users who would not benefit | Value-fit gate, before the budget | `f2g/ml/policy.py` |",
        "| Contacting users harmed by contact | Non-positive uplift excluded unconditionally | `f2g/ml/policy.py` |",
        "| Conversion win masking a retention loss | Harm checked before success in the stopping rules | `f2g/experiment/analysis.py` |",
        "| Declaring a win by repeated peeking | Always-valid confidence sequences | `f2g/experiment/analysis.py` |",
        "",
        "## Reproducing every number here",
        "",
        "```bash",
        "python -m f2g.data.generate      # the population",
        "python -m f2g.ml.train           # models and metrics",
        "python -m f2g.ml.run_policy      # targeting decisions and offline evaluation",
        "python -m f2g.evals.run          # agent safety gate",
        "python -m f2g.governance.model_card   # regenerate this card",
        "```",
        "",
    ]
    return "\n".join(lines)


def generate() -> str:
    model_report = _load(REPORT_DIR / "model_evaluation.json")
    policy_report = _load(REPORT_DIR / "policy_report.json")
    eval_path = EVAL_DIR / "latest.json"
    eval_report = json.loads(eval_path.read_text(encoding="utf-8")) if eval_path.exists() else None
    return render(model_report, policy_report, eval_report)


def main() -> None:
    card = generate()
    CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    CARD_PATH.write_text(card, encoding="utf-8")
    print(f"model card -> {CARD_PATH} ({len(card.splitlines())} lines)")


if __name__ == "__main__":
    main()
