import { useEffect, useState } from "react";
import { api, type Health } from "./lib/api";
import { CohortView } from "./components/CohortView";
import { NudgePreview } from "./components/NudgePreview";
import { ChatPanel } from "./components/ChatPanel";
import { ExperimentDashboard } from "./components/ExperimentDashboard";
import { Badge } from "./components/common";

type Tab = "cohort" | "agent" | "experiment";

const TABS: { id: Tab; label: string }[] = [
  { id: "cohort", label: "Targeting" },
  { id: "agent", label: "Concierge" },
  { id: "experiment", label: "Experiment" },
];

function useTheme() {
  const [theme, setTheme] = useState<"light" | "dark" | null>(
    () => (localStorage.getItem("f2g-theme") as "light" | "dark" | null) ?? null,
  );
  useEffect(() => {
    // No stamp means "follow the OS", which is the default the tokens assume.
    if (theme) document.documentElement.setAttribute("data-theme", theme);
    else document.documentElement.removeAttribute("data-theme");
    if (theme) localStorage.setItem("f2g-theme", theme);
    else localStorage.removeItem("f2g-theme");
  }, [theme]);
  return { theme, setTheme };
}

export default function App() {
  const [tab, setTab] = useState<Tab>("cohort");
  const [userId, setUserId] = useState<string | null>(null);
  const [provider, setProvider] = useState("deterministic");
  const [health, setHealth] = useState<Health | null>(null);
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    api.health().then(setHealth).catch(() => setHealth(null));
  }, []);

  return (
    <div className="shell">
      <header className="masthead">
        <h1>Free2Genius</h1>
        <span className="sub">
          uplift targeting · evidence-grounded concierge · always-valid experiment
        </span>
        <button
          className="theme-toggle"
          onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
        >
          {theme === "dark" ? "Light" : "Dark"} theme
        </button>
      </header>

      <div className="synthetic-banner">
        <strong>Synthetic data.</strong> Every user, transaction, fee and price shown here is
        generated by <code>f2g/data/generate.py</code>. This is not Albert data and the pricing
        is illustrative.
      </div>

      <nav className="tabs" role="tablist">
        {TABS.map((t) => (
          <button
            key={t.id}
            role="tab"
            className="tab"
            aria-selected={tab === t.id}
            onClick={() => setTab(t.id)}
          >
            {t.label}
          </button>
        ))}
        <div style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center",
                      paddingBottom: 6 }}>
          {health && (
            <Badge tone={health.status === "ok" ? "ok" : "warn"}>
              api {health.status}
              {health.llm.provider ? ` · ${health.llm.provider}` : ""}
            </Badge>
          )}
        </div>
      </nav>

      {tab === "cohort" && (
        <CohortView selected={userId} onSelect={(id) => { setUserId(id); setTab("agent"); }} />
      )}

      {tab === "agent" && (
        <div className="grid" style={{ gap: 16 }}>
          {userId && (
            <p className="note" style={{ marginTop: 0 }}>
              Showing <span className="mono">{userId}</span> ·{" "}
              <button className="ghost" onClick={() => setTab("cohort")}>
                pick a different user
              </button>
            </p>
          )}
          <NudgePreview userId={userId} provider={provider} onProviderChange={setProvider} />
          <ChatPanel userId={userId} provider={provider} onProviderChange={setProvider} />
        </div>
      )}

      {tab === "experiment" && <ExperimentDashboard />}

      <footer className="note" style={{ marginTop: 32 }}>
        {health?.llm?.egress && <>Inference egress: {health.llm.egress}. </>}
        No authentication is configured — this is a demonstration service and must not be
        exposed publicly.
      </footer>
    </div>
  );
}
